### ISSUE TITLE
Translate "steps" for "Fases" in catalan and spanish for participatory processes

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim.barcelona#643] opened 2016-10-25 09:37 UTC
Please translate them on the admin panel.

**Comment by josepjaume** [comment] 2016-10-26 14:58
Dupe of #644

**Comment by andreslucena** [comment] 2016-10-27 08:18
Ok, closing #644 as duplicated.

**Comment by andreslucena** [comment] 2017-04-24 14:56
Closing as fixed on new version

**Closed as completed by andreslucena** 2017-04-24 14:56 UTC
Labels: enhancement, nice-to-have
